### ISSUE TITLE
"the number" shows numerous wishlist entries with extended mag in first column

### ISSUE THREAD

**Issue by deangaudet** [48klocs/dim-wish-list-sources#72]
on gun "the number", extended mag shouldn't be in the barrel column for wishlist rolls:

![image](https://user-images.githubusercontent.com/76624780/151646331-d5fa283c-5e33-4796-807a-dc18fe6e0ae9.png)

**Comment by Deanosim** [comment]
Looks like a mistake by me, somehow ended up as Extended Mag instead of Extended barrel.
The orignal image from Chevy's discord shows extended/arrowhead I probably got confused.
![image0](https://user-images.githubusercontent.com/4834976/151651681-b0b06bb2-a2f1-4686-af67-aa3c2f3f4278.png)

I'll see about getting it fixed asap.
